"""Regression lock on the v2.1.0 Agent-호출-권한 artifact.

Two things can regress here without the file names changing, and only one of
them is visible in a diff summary:

1. The *scope* silently widens. `templates/shared/agent-tool-permission.md`
   grants standing permission for the Agent tool only; Workflow and
   deep-research are excluded by name. Delete that sentence and the file still
   parses, still loads, still reads like a permission — it just grants more
   than anyone approved. That is the security surface of this feature.
2. The `#### 4f` write contract loses its narrow `.gitignore` rule and starts
   ignoring `.claude/` wholesale, silently untracking a target repo's
   `.claude/settings.json`.

Both assertions are scoped to the body that owns the rule and match a phrase
unique to that body — a phrase that also appears in a heading or in the Step 5
summary would leave the lock satisfiable after the rule itself is deleted.
"""

from __future__ import annotations

import unittest
from pathlib import Path

PLUGIN = Path(__file__).resolve().parents[1]
COMMAND = PLUGIN / "commands" / "project-init.md"
TEMPLATE = PLUGIN / "templates" / "shared" / "agent-tool-permission.md"


def section(text: str, start_marker: str, end_marker: str) -> str:
    """Body between two markers, exclusive of the end marker; both must be unique."""
    for label, marker in (("start", start_marker), ("end", end_marker)):
        if text.count(marker) != 1:
            raise AssertionError(f"{label} marker not unique: {marker!r}")
    start = text.index(start_marker)
    end = text.index(end_marker, start + len(start_marker))
    return text[start:end]


def flat(text: str) -> str:
    """Collapse all whitespace runs to single spaces.

    The templates are hard-wrapped, so a phrase the rule owns can straddle a
    newline. A lock that matches raw text would then fail on a reflow — a
    cosmetic edit — and, worse, would tempt whoever hits that red into weakening
    the assertion instead of restoring the rule.
    """
    return " ".join(text.split())


def paragraph_starting(text: str, prefix: str) -> str:
    """The single blank-line-delimited paragraph beginning with `prefix`."""
    hits = [p for p in text.split("\n\n") if p.lstrip().startswith(prefix)]
    if len(hits) != 1:
        raise AssertionError(f"expected exactly one paragraph starting {prefix!r}, found {len(hits)}")
    return hits[0]


class TestPermissionTemplate(unittest.TestCase):
    def setUp(self) -> None:
        self.assertTrue(TEMPLATE.exists(), f"template missing: {TEMPLATE}")
        self.text = TEMPLATE.read_text(encoding="utf-8")
        self.flat = flat(self.text)

    def test_scope_excludes_workflow_and_deep_research_by_name(self) -> None:
        # The label alone is header-satisfiable: keep it, drop the two names, and
        # a substring search on the label still passes while the scope is now
        # unbounded. Assert the names inside the paragraph the label owns.
        para = flat(paragraph_starting(self.text, "**Out of scope"))
        self.assertIn("Workflow", para)
        self.assertIn("deep-research", para)

    def test_grant_is_stated(self) -> None:
        self.assertIn("standing-approved in this repository", self.flat)

    def test_fan_out_declaration_duty_survives(self) -> None:
        # The Subagent-spray anti-pattern is what keeps this grant bounded.
        self.assertIn("Undeclared large-scale dispatch is not covered by this grant", self.flat)

    def test_template_is_english(self) -> None:
        # The artifact ships into arbitrary target repos and is read by the model,
        # so it is exempt from this repo's Korean-primary doc convention. Locking
        # the absence of Hangul keeps a future Korean-primary sweep from silently
        # reverting it.
        hangul = [c for c in self.text if "\uac00" <= c <= "\ud7a3" or "\u3131" <= c <= "\u318e"]
        self.assertEqual(hangul, [], f"template must be English, found: {hangul[:10]}")

    def test_carries_no_provenance_or_backstory(self) -> None:
        # Provenance and self-justification are token waste and distort meaning:
        # they shift the reader from "what must I do" to "why does this exist",
        # and a justification sentence reads as an instruction. Rationale belongs
        # in the CHANGELOG and the PR, not in the artifact.
        for banned in ("project-init", "generated by", "This file was", "Claude Code"):
            self.assertNotIn(banned, self.text)

    def test_no_unsubstituted_placeholder(self) -> None:
        # 4f writes this template verbatim; a placeholder here would ship raw.
        self.assertNotIn("{{", self.text)


class TestCommandContract(unittest.TestCase):
    def setUp(self) -> None:
        self.text = COMMAND.read_text(encoding="utf-8")

    def test_step_and_publish_block_exist_exactly_once(self) -> None:
        self.assertEqual(self.text.count("### Step 3.6:"), 1)
        self.assertEqual(self.text.count("#### 4f:"), 1)

    def test_question_step_declares_independence_and_skip(self) -> None:
        step = section(self.text, "### Step 3.6:", "### Step 4:")
        step = flat(step)
        self.assertIn("합산하지 않는다", step)
        self.assertIn("4f를 skip한다", step)

    def test_publish_block_writes_the_repo_scoped_path(self) -> None:
        # Scoped to the 4f window on purpose: the same path string also appears
        # in the Step 5 summary, so a file-wide search would stay green after
        # the write instruction itself was moved or deleted.
        block = section(self.text, "#### 4f:", "### Step 5:")
        block = flat(block)
        self.assertIn("templates/shared/agent-tool-permission.md", block)
        # Bound to the write verb, not merely present in the window: the same
        # path also appears in this block's .gitignore step, so a bare presence
        # check stays green after the write instruction stops naming its
        # destination. A mutation proved exactly that.
        self.assertIn("`.claude/rules/agent-tool-permission.md`에 쓴다", block)

    def test_publish_block_keeps_gitignore_narrow(self) -> None:
        block = section(self.text, "#### 4f:", "### Step 5:")
        block = flat(block)
        self.assertIn(".gitignore", block)
        self.assertIn("통째를 무시하지 않는다", block)

    def test_publish_block_forbids_linking_from_agents_md(self) -> None:
        # A committed doc pointing at a git-excluded file becomes a broken
        # link for whoever clones the repo.
        block = section(self.text, "#### 4f:", "### Step 5:")
        block = flat(block)
        self.assertIn("링크하지 않는다", block)

    def test_template_is_listed_for_reading(self) -> None:
        reads = section(self.text, "#### 4a:", "#### 4b:")
        reads = flat(reads)
        self.assertIn("templates/shared/agent-tool-permission.md", reads)


if __name__ == "__main__":
    unittest.main()
